hiwi_portal/urls.py
from django.conf.urls import url

from . import views
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    url(r'^profile/contract/[0-9]+/delete$', views.delete_contract, name='contract delete'),
    url(r'^work/[0-9]+/delete$', views.delete_work, name='work delete'),
    url(r'^contract/([0-9]+)/(10|11|12|[1-9])/([0-9]{4})/print/$', views.printView, name='print'),
    url(r'^profile/contract/add/$', views.contractAdd, name='contractAdd'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/delete$', views.delete_profile, name='delete profile'),
    url(r'^profile/work-dust$', views.work_dust, name='workduster'),
    url(r'^profile/work-dust/add/anual$', views.wd_manage_anual, name='wd_manage_anual'),
    url(r'^profile/work-dust/add/fill$', views.wd_manage_fill, name='wd_manage_fill'),
    url(r'^profile/work-dust/apply/(10|11|12|[1-9])/([0-9]{4})/([0-9]+)$', views.wd_manage_apply,
        name='wd_manage_apply'),
    url(r'^profile/work-dust/weekly/([0-9]+)/delete$', views.wd_delete_anual, name='wd_manage_delte'),
    url(r'^profile/work-dust/filler/([0-9]+)/delete$', views.wd_delete_filler, name='wd_manage_delte'),
    url(r'^$', views.index, name='index'),
    url(r'^faq/$', views.faq, name='faq'),
]

hiwi_stunden/urls.py
from django.urls import path, re_path, include
import os
from django.contrib.auth import views as auth_views
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    re_path(r'^', include('hiwi_portal.urls')),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'),
            name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

hiwi_portal/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import UserManager
from django.core.validators import RegexValidator
from django.core.validators import EmailValidator
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
import time
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ValidationError


#
class User(models.Model):
    is_anonymous = False
    is_authenticated = True

    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    kitaccount = models.CharField(max_length=32, unique=True)  # funfact: old MS legacy :)
    email = models.CharField(max_length=200)
    private_email = models.CharField(max_length=200, null=True, validators=[EmailValidator()], blank=True)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
    REQUIRED_FIELDS = ['firstname', 'lastname', 'email']
    USERNAME_FIELD = 'kitaccount'
    objects = UserManager()
    notify_to_private = models.BooleanField(default=False)
    work_dusted = models.BooleanField(default=False)

    def set_unusable_password(self):
        pass

    def get_username(self):
        return self.kitaccount

    def set_password(self, pw):
        pass


class Hiwi(User):
    pass


class Department(models.Model):
    name = models.CharField(max_length=200)


class Supervisor(User):
    department = models.ForeignKey(Department, null=True, on_delete=models.SET_NULL)


class Contract(models.Model):
    PERSONELL_DEPARTMENTS = (
        ('GF', 'Großforschungsbereich'),
        ('UB', 'Universitätsbereich'),
    )
    user = models.ForeignKey(Hiwi, on_delete=models.CASCADE)
    department = models.CharField(max_length=200)
    hours = models.PositiveIntegerField(validators=[MaxValueValidator(85)])
    payment = models.DecimalField(max_digits=6, decimal_places=2)
    personell = models.CharField(max_length=2, choices=PERSONELL_DEPARTMENTS)
    personell_number = models.CharField(max_length=200)
    contract_begin = models.DateField('Vertragsstart')
    contract_end = models.DateField('Vertragsende')
    vacation = models.PositiveIntegerField()

    @property
    def current_worklog(self):
        return self.cw


class WorkLog(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    printed = models.BooleanField(default=False)
    carer_signed = models.BooleanField(default=False)
    month = models.IntegerField()
    year = models.IntegerField()

    def getWorkLog(self, contract, month, year):
        try:
            if contract.contract_begin.year > year or \
                            contract.contract_end.year < year or \
                    (contract.contract_begin.year == year and contract.contract_begin.month > month) or \
                    (contract.contract_end.year == year and contract.contract_end.month < month):
                raise ValidationError("Invalid workLog (shouldn't happen)")
            workL = WorkLog.objects.get(contract=contract, month=month, year=year)
        except ObjectDoesNotExist:
            workL = WorkLog()
            workL.month = month
            workL.year = year
            workL.contract = contract
            workL.save()
        return workL

    def calc_over_work(self):
        over = 0.0
        lastLog = None
        lastMonth = self.month - 1;
        lastYear = self.year
        if lastMonth == 0:
            lastMonth = 12
            lastYear = lastYear - 1
        try:
            lastLog = self.getWorkLog(self.contract, lastMonth, lastYear)
        except ValidationError:
            pass
        if not lastLog == None:
            lastLogCalc = lastLog.calcHours()
            over = (lastLogCalc - self.contract.hours)
        return over

    def calcHours(self, withOver=True):
        workSum = float(round(self.contract.vacation / 12.0))
        if withOver:
            workSum += self.calc_over_work()
        logs = self.worktime_set.all()
        for l in logs:
            workSum += l.hours()
        return workSum


class WorkTime(models.Model):
    work_log = models.ForeignKey(WorkLog, on_delete=models.CASCADE)
    pause = models.PositiveIntegerField(default=0)
    begin = models.DateTimeField('Start')
    end = models.DateTimeField('Ende')
    activity = models.CharField(max_length=200)

    def hours(self):
        start_stamp = time.mktime(self.begin.timetuple())
        end_stamp = time.mktime(self.end.timetuple())
        return round((((end_stamp - start_stamp) - float(self.pause) * 60 * 60) / 60.0 / 60.0) * 100) / 100.0

    def getWorkLog(self, contract, month, year):
        try:
            if contract.contract_begin.year > year or \
                            contract.contract_end.year < year or \
                    (contract.contract_begin.year == year and contract.contract_begin.month > month) or \
                    (contract.contract_end.year == year and contract.contract_end.month < month):
                raise ValidationError("Invalid workLog (shouldn't happen)")
            workL = WorkLog.objects.get(contract=contract, month=month, year=year)
            workSum = workL.calcHours()
        except ObjectDoesNotExist:
            workL = WorkLog()
            workL.month = month
            workL.year = year
            workL.contract = contract
            workL.save()
        return workL

    def getNextWorkLog(self, contract, month, year):
        nextMonth = month + 1
        nextYear = year
        if nextMonth > 12:
            nextMonth = 1
            nextYear += 1
        return self.getWorkLog(contract, nextMonth, nextYear)

    def clean_fields(self, year=-1, month=-1):
        super(WorkTime, self).clean_fields()
        startStamp = time.mktime(self.begin.timetuple())
        endStamp = time.mktime(self.end.timetuple())
        contract = self.work_log.contract
        if contract.contract_begin.year > year or \
                        contract.contract_end.year < year or \
                (contract.contract_begin.year == year and contract.contract_begin.month > month) or \
                (contract.contract_end.year == year and contract.contract_end.month < month):
            raise ValidationError("Date out of contract.")
        if self.begin.weekday() > 4:
            raise ValidationError("You can only work from Mon to Fri.")
        if self.begin.hour < 6 or self.end.hour > 20 or (self.end.hour == 20 and self.end.minute > 0):
            raise ValidationError("You can only work at daytime (06-20h). Sorry coffee nerds ;(")
        if self.end.hour - self.begin.hour - int(self.pause) > 10:
            raise ValidationError("You can only work 10 hours a day.")
        if self.end.hour - self.begin.hour > 6 and int(self.pause) < 1:
            raise ValidationError("You have to make a break of at least 1 hour.")
        if startStamp >= endStamp:
            raise ValidationError(
                'The start time have to be before the end time. In case of a flux capacitor incident please contact the technical support.')
        if (int(self.pause) * 60 * 60) >= endStamp - startStamp:
            raise ValidationError("Such error, many pause!")
        if self.hours() == 0:
            raise ValidationError("Worktime caped to 0.")
        if self.work_log.calcHours() + self.hours() > contract.hours:
            if (
                            month == contract.contract_end.month and year == contract.contract_end.year) or self.work_log.calcHours() + self.hours() > round(
                        contract.hours * 1.5):
                raise ValidationError("Max. monthly worktime exceeded!")


class FixedWorkDustActivity(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    avg_length = models.FloatField(validators=[MinValueValidator(0.1)])
    start = models.TimeField('Start')
    week_day = models.PositiveIntegerField(validators=[MaxValueValidator(4)])


class FillerWorkDustActivity(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    avg_length = models.FloatField(validators=[MinValueValidator(0)])

templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Hiwi Portal - {% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <link rel="stylesheet" href="{% static "css/jquery-ui.min.css" %}">
          <link rel="stylesheet" href="{% static "css/jquery-ui-timepicker-addon.css" %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">

        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "css/portal.css" %}">
    </head>
    <body>
      {% load mytags %}
      <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">Hiwi Portal <small><span class="label label-default">BETA</span></small></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav">
            <li class="{% active '^/$' %}"><a href="/">Your Work</a></li>
            <li class="{% active '^/faq/$' %}"><a href="/faq">FAQ</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="dropdown  {% active '^/profile/.*' %}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{user.firstname}} {{user.lastname}} ({{user.kitaccount}}) <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="{% active '^/profile/$' %}"><a href="/profile">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
        </li>
            {% else %}
            <li class="{% active '^/login/.*' %}"><a href="/login">Login</a></li>
            {% endif %}
           </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
     <script src="{% static "js/jquery.min.js" %}"></script>
     <script src="{% static "js/jquery-ui.min.js" %}"></script>
     <script src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
     <script src="{% static "js/bootstrap.min.js" %}"></script>
     <div class="container">
 {% block content %}{% endblock %}
 <hr/>
 <span class="subtext">Build with <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span> by <i>someone</i>. Released under the MIT License. Code availiable on <a href="https://github.com/janisstreib/hiwi-stunden">GitHub</a>.</span>
</div>
<script>
$(function() {
  $( ".datepicker" ).each(function( index ) {
    $( this ).datepicker();
    if($(this).val())
      $(this).datepicker('setDate', $.datepicker.parseDate('yy-mm-dd', $(this).val()));
    $( this ).datepicker("option", "dateFormat", "yy-mm-dd");
});
  $('[data-toggle="tooltip"]').tooltip({html: true});
$( ".timepicker" ).each(function( index ) {
  $( this ).timepicker();
});
});
</script>
 </body>
 </html>

templates/contract_add.html
{% extends "base.html" %}
{% block title %}New contract{% endblock %}

{% block content %}


<h1>Add contract</h1>
{% include "errorhandle.html" %}
<form method="POST" action="/profile/contract/add/">
{% csrf_token %}
<table class="table">
<tr>
  <th>Institute</th><td><input class="form-control" id="institute" name="institute" type="text" value="{{postdata.institute}}" /></td>
</tr>
<tr>
  <th>Personell id</th><td><input class="form-control" id="personell-id" name="personell_id" type="text" value="{{postdata.personell_id}}"/></td>
</tr>
<tr>
  <th>Personell department</th><td><select name="dp"><option {% ifequal postdata.dp "GF"%}selected="selected"{%endifequal%}>GF</option><option {% ifequal postdata.dp "UB"%}selected="selected"{%endifequal%}>UB</select></td>
</tr>
<tr>
  <th>Contract start</th><td><input class="form-control datepicker" id="contract-start" name="contract_start" type="text" value="{{postdata.contract_start}}"/></td>
</tr>
<tr>
  <th>Contract end </th><td><input class="form-control datepicker" id="contract-end" name="contract_end" type="text" value="{{postdata.contract_end}}"/></td>
</tr>
<tr>
  <th>Work hours</th><td><input class="form-control" id="work-hours" name="work_hours" type="text" value="{{postdata.work_hours}}"/></td>
</tr>
<tr>
  <th>Payment/hour</th><td><input class="form-control" id="payment" name="payment" type="text" value="{{postdata.payment}}"/></td>
</tr>
<tr>
  <th></th><td><input type="submit" class="pull-right btn btn-primary" value="Add"/></td>
</tr>
</table>
</form>
{% endblock %}

templates/errorhandle.html
{% if error %}
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <b>Error:</b>
  <ul>
    {% for e in error %}
    <li>{{ e }}</li>
    {% endfor %}
  </ul>
</div>
{% elif post %}
<div class="alert alert-success" role="alert">
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
  <b>Success!</b> Your data was saved successfully.
</div>
{% endif %}

templates/faq.html
{% extends "base.html" %}
{% block title %}FAQ{% endblock %}
{% block content %}
<div class="page-header">
  <h1>FAQ</h1>
</div>

<ul>
  <li><span class="quest">What is this?</span>A portal for SCC-NET Hiwis to keep track of their working hours.</li>
  <li><span class="quest">What about privacy?</span>All your data will be completly erased after 2 months of inactivity (TODO).</li>
</ul>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">Your username and password didn't match. Please try again.</div>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
  <div class="form-group">
    <label for="id_username">KIT-Account</label>
    <input type="text" id="id_username" type="text" name="username" class="form-control" placeholder="KIT-Account">
  </div>
  <div class="form-group">
    <label for="id_password">Password</label>
    <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">Logout successful.</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="page-header">
<h1>Your profile</h1>
</div>
{% include "errorhandle.html" %}
<h2>Your data</h2>
<script>
var clicks=0;
function accountDelete() {
  clicks++;
  if(clicks == 5)
    {
      window.location = "work-dust";
      return false;
    }
  return confirm('Do you really want to delete all your data?');
}
</script>
<form method="POST" action="/profile/">
<table class="table">
  {% csrf_token %}
  <tr>
    <th>KIT-account</th>
    <td><input class="form-control" id="kit-acc" type="text" value="{{user.kitaccount}}" disabled></td>
  </tr>
  <tr>
    <th>Firstname</th>
    <td><input class="form-control" id="fn" type="text" value="{{user.firstname}}" disabled></td>
  </tr>
  <tr>
    <th>Surname</th>
    <td><input class="form-control" id="sn" type="text" value="{{user.lastname}}" disabled></td>
  </tr>
  <tr>
    <th>Password</th>
    <td>Changable at the <a href="https://campus.studium.kit.edu/">Campus Management Portal</a> (student accounts) or the <a href="https://intra.kit.edu">KIT Intranetportal</a> (partner/guest accounts).</td>
  </tr>
  <tr>
    <th>E-Mail</th>
    <td><input class="form-control" id="kit-mail" type="text" value="{{user.email}}" disabled></td>
  </tr>
  <tr>
    <th>Private E-Mail<span class="help-block">Optional</span></th>
    <td><input class="form-control" name="private_email" id="private-mail" type="text" value="{% if user.private_email %}{{user.private_email}}{% endif %}" ></td>
  </tr>
  <tr><td></td><td><input name="private_notif" type="checkbox" {% if user.notify_to_private %} checked {%endif%}/> Send notifications to my private E-Mail address specified above.</td></tr>
  <tr>
    <th>Phone number<span class="help-block">Optional</span></th>
    <td><input name="phone" class="form-control" id="phone" type="text" value="{% if user.phone_number %}{{user.phone_number}}{% endif %}" ></td>
  </tr>
  <tr><td></td><td><input type="submit" name="data" value="Save" class="btn btn-primary pull-right"/></td></tr>
</table>
</form>

<h2>Your work settings</h2>
<div class="panel panel-default">
  <div class="panel-heading">Your contracts</div>
  <div class="panel-body">
    <p>Add and manage your hiwi contracts with the KIT below. Enter them as they should appear on the monthly document.</p>
  </div>
  <table class="table">
    <tr>
      <th>Institute</th><th>Personell id</th><th>Personell department</th><th>Contract start</th><th>Contract end</th><th>Work hours</th><th>Payment/hour</th><th>Vacation hours/year <span data-toggle="tooltip" data-placement="bottom" title="Calculated as follows:<br/>(hours * 200 * 3,95)/85" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></th><th><a href="contract/add" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></th>
    </tr>
    {% for c in user.contract_set.all %}
      <tr>
        <td>{{c.department}}</td><td>{{c.personell_number}}</td><td>{{c.personell}}</td><td>{{c.contract_begin}}</td><td>{{c.contract_end}}</td><td>{{c.hours}}</td><td>{{c.payment}} €</td><td>{{c.vacation}}<td><a href="/profile/contract/{{c.id}}/delete" class="btn btn-primary"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
<hr/>
{% if user.work_dusted %}
<h2 id="wd">Magic WorkDust</h2>
{% for c in user.contract_set.all %}
<div class="panel panel-default">
	<div class="panel-heading">WorkDust settings for <b>{{c.department}}</b> ({{c.contract_begin}} - {{c.contract_end}})</div>
  <div class="panel-body">
    <p>Add and manage your templates for automatic filling.</p>
  </div>
  <b>Weekly activities</b>
  <table class="table">
    <tr>
      <th>Activity</th><th>Day of week</th><th>Start</th><th>Average duration</th><th></th>
    </tr>
    {% for sa in c.fixedworkdustactivity_set.all%}
    <tr>
      <td>{{sa.description}}</td><td>{{sa.week_day}}</td><td>{{sa.start}}</td><td>{{sa.avg_length}}</td><td><a href="/profile/work-dust/weekly/{{sa.id}}/delete" class="btn btn-primary"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
    </tr>
    {%endfor%}
    <tr>
      <form method="POST" action="work-dust/add/anual">
        <input type="hidden" name="contract" value="{{c.id}}"/>
        {% csrf_token %}
      <td><input class="form-control" type="text" name="description"/></td><td><select class="form-control" name="weekday">
        <option value="0">Monday</option>
        <option value="1">Tuesday</option>
        <option value="2">Wednesday</option>
        <option value="3">Thursday</option>
        <option value="4">Friday</option>
      </select><td><input type="text" name="start" class="form-control timepicker"></td><td><input class="form-control" type="text" name="dur"/></td><td><input class="btn btn-primary" type="submit" value="OK"/></td>
    </form>
    </tr>
  </table>
  <b>Filling activities</b>
  <table class="table">
    <tr>
      <th>Activity</th><th>Average duration</th><th></th>
    </tr>
    {% for sa in c.fillerworkdustactivity_set.all%}
    <tr>
      <td>{{sa.description}}</td><td>{{sa.avg_length}}</td><td><a href="/profile/work-dust/filler/{{sa.id}}/delete" class="btn btn-primary"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
    </tr>
    {%endfor%}
    <tr>
      <form method="POST" action="work-dust/add/fill">
        <input type="hidden" name="contract" value="{{c.id}}"/>
        {% csrf_token %}
      <td><input class="form-control" type="text" name="description"/></td><td><input class="form-control" type="text" name="dur"/></td><td><input class="btn btn-primary" type="submit" value="OK"/></td>
    </form>
    </tr>
  </table>
</div>
{%endfor%}
<hr/>
{%endif%}
<h1>Danger zone</h1>
<h2>Erase all data</h2>
<p>Hereby, all your work hours, contracts, your private mail and phone number stored on this site will be
instantaneously erased.</p>
<form action="/profile/delete" method="POST" onsubmit="return accountDelete();">
{% csrf_token %}
<input type="submit" class="btn btn-danger" href="/profile/delete" value="Erase all account data"/>
</form>
{% endblock %}